SOLVER:
  BATCH_SIZE: 64
  MAX_EPOCH: 10
  LR: 8e-4
  SEED: 600

DECODER:
  BINARY: 4

protein_encode:
  input: "prottrans"  #integer prottrans
  encoder: "LA" #LA cnn

RESULT:
  OUTPUT_DIR: "./result/independent_test"